
    /**
     * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
     * Do not edit manually unless you know what you are doing.
    */


    #define CALIBRATION_H

    const int acc_off_x = -50;
    const int acc_off_y = -5;
    const int acc_off_z = 20;
    const float acc_scale_x = 534.773595;
    const float acc_scale_y = 1151.972191;
    const float acc_scale_z = 1113.442809;

    const int magn_off_x = -28;
    const int magn_off_y = -67;
    const int magn_off_z = 28;
    const float magn_scale_x = 460.949274;
    const float magn_scale_y = 570.947388;
    const float magn_scale_z = 443.473482;

    const float magn_misalign_Mxx = 0.974775;
    const float magn_misalign_Mxy = -0.222873;
    const float magn_misalign_Mxz = 0.011895;

    const float magn_misalign_Myx = -0.082773;
    const float magn_misalign_Myy = 0.996515;
    const float magn_misalign_Myz = 0.010343;

    const float magn_misalign_Mzx = -0.086375;
    const float magn_misalign_Mzy = -0.162879;
    const float magn_misalign_Mzz = 0.982858;
    